import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-treatment',
  templateUrl: './treatment.component.html',
  styleUrls: ['./treatment.component.scss']
})
export class TreatmentComponent implements OnInit {

  treatments:any = [
    {heading:'Social Media Addiction',text:'',image:'assets/images/treatments/social_media_addiction.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Social media addiction is a behavioral addiction that is defined by being overly concerned about social media, ruled out by an unavoidable urge to log on to or use social media, devoting so much time and effort to social media that it starts to affect some other life aspects. '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Smoking & Tobaco Addiction',text:'',image:'assets/images/treatments/smoking_tobaco_addiction.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Schizophrenia Treatment',text:'',image:'assets/images/treatments/schizophrenia.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Schizophrenia is a serious mental disorder where people are not able to interpret reality. Schizophrenia results in a combination of delusions, disordered thinking, and behavior that messes with a person’s daily routine and functioning. People with schizophrenia require proper treatment. You can now get the best treatment for schizophrenia in Gurgaon with the help of our rehabilitation centre.'},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Obsessive Complusive Disorder',text:'',image:'assets/images/treatments/obsessive_compulsive_disorder.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Anxiety Management',text:'',image:'assets/images/treatments/anxiety_management.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Bipolar Effective Disorder',text:'',image:'assets/images/treatments/bipolar_effective_disorder.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'DEPRESSION',text:'',image:'assets/images/treatments/depression.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Drug Addiction Treatment',text:'',image:'assets/images/treatments/drug_addiction_treatment.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Depressive disorder is more than just feeling sad, it is a serious mental health condition that requires proper attention and medical care. Depression can be devastating if not paid attention to. With an early diagnosis, treatment is possible and the person will be able to resume his normal life. Some people experience at least one episode of depression once in their lifetime whereas the people with depressive disorder experience episodes which last for months and sometimes for years. Treatment is necessary for depression and our rehabilitation center offers the best treatment for depression in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Alcohol Addiction',text:'',image:'assets/images/treatments/alcohol_addiction.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Alcohol addiction is a chronic disease characterized by uncontrolled drinking and preoccupation with alcohol. It is the inability to control drinking due to physical and emotional dependence on alcohol. Alcohol consumption is quite common, but some people lose control of it irrespective of the severe psychological and physical consequences of excessive drinking. Medical help and social support are two great methods that can treat alcohol addiction. Humana Wellness is one of the best alcohol rehabilitation centre in Delhi NCR and Gurgaon known for giving out the best alcohol addiction treatment in Delhi NCR and Gurgaon.'},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }},
    {heading:'Gambling Addiction',text:'',image:'assets/images/treatments/gambling_addiction.png',details:{
      heading:'DEPRESSION TREATMENT CENTRE IN GURGAON',
      top:{heading:'DEPRESSION',image:'assets/images/treatments/depression/top_image.jpg',text:'Gambling is an enjoyable activity for many people but over time, some people develop gambling addiction which can ruin their lives. Gambling addiction is a progressive illness that can evolve into a huge problem one day or other. It is obsessive and compulsive as well, the urge can be overwhelming and the gambler would lie, cheat, manipulate, steal to indulge himself in gambling. This is when treatment becomes necessary for the person. The best treatment for gambling addiction is available in Gurgaon.  '},
      symptoms:{heading:'What are the symptoms of depression??',subheading:'Depression presents different symptoms, depending upon the person. Common symptoms include:',points:[{name:'Less activity'},{name:'Guilt and hopelessness'},{name:'LAck of interest'},{name:'No concentration'},{name:'Suicidal thoughts'},{name:'Physical pain'},{name:'Loss of energy'},{name:'Changes in eating habits'},{name:'Sleep routine changes'}]},
      cause:{heading:'Causes',text:'Depression never has a single cause; it can be triggered by a life crisis or by physical illness. Some of the major causes are:',cards:[{heading:'Life circumstances',text:'Relationship changes, financial changes, and marital status changes can trigger depression.'},{heading:'Brain changes',text:'Research says that the frontal lobe of the brain becomes less active when a person is depressed and depression is associated with changes in how the pituitary gland responds to hormone stimulation.'},{heading:'Trauma',text:'When people experience trauma at an early age, it can cause long-term changes in how their brain responds to fear and stress which might cause depression.'},{heading:'Genetic',text:'Mood disorders tend to be running in families so anyone can catch depression.'},{heading:'Alcohol and drug misuse',text:'Adults who are addicted to any kind of substance are prone to catch depression as their life falls.'}]},
      treatment:{heading:'Diagnosis and treatment',subheading:'A person must have has at least one depressive episode to be diagnosed with depression. The symptoms of a depressive episode include:',points:[{name:'Change in weight'},{name:'Difficulty in making decision'},{name:'Suicidal intentions'},{name:'Feelings of low self-worth'},{name:'Sleeping issues'},{name:'Loss of interest'}],text:'The doctor will examine and if you are diagnosed with depression, you would be asked to get into treatment. Our rehabilitation center gives out the <b>best treatment for depression in Gurgaon.</b><br>Depression responds to treatment and the person can recover from this state. Safety planning is important for people who get suicidal thoughts. A combination of medications and therapy is considered the best treatment for depression. The treatment plan includes:',cards:[{heading:'Psychotherapy',text:'Includes cognitive-behavioral therapy, family-focused therapy, and interpersonal therapy which help the person in taking control over his/her mind.'},{heading:'Medicines',text:'Antidepressants and antipsychotic medicines are only given as per the prescription of the doctor.'},{heading:'Yoga and meditation',text:'Help the patient to feel relaxed and help with mild-to-moderate symptoms.'},{heading:'Brain stimulation therapy',text:'These therapies are tried only if psychotherapy and medication do not work on the patient and he/she needs more advanced treatment. Repetitive Tran’s cranial magnetic stimulation is recommended to cure severe depression.'}]}
    }}
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
